QLTour/QLTour/Controllers/BookTourController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using QLTour.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLTour.Controllers
{
    [Authorize(Roles = "")]
    public class BookTourController : Controller
    {
        private QLTourEntities db = new QLTourEntities();
        // GET: BookTour
        public ActionResult Index(int id, int SoVe = 1)
        {
            ViewBag.ID = id;
            var tour = db.Tours.FirstOrDefault(s => s.ID == id);

            ViewBag.SoVe = SoVe;
            ViewBag.Gia = tour.Gia;
            ViewBag.NgayKhoiHanh = tour.NgayKhoiHanh;
            ViewBag.TourID = tour.ID;
            ViewBag.Ten = tour.Ten;
            ViewBag.DiemDen = tour.DiaDiem1.Ten;
            ViewBag.Button = 0;
            ViewBag.NganHang = new SelectList(db.NganHangs, "ID", "Ten");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Include = "TenChuTaiKhoan, SoTaiKhoan, NganHangID")] TaiKhoan taiKhoan, int SoVe, int TourID)
        {
            var tour = db.Tours.FirstOrDefault(s => s.ID == TourID);

            if (ModelState.IsValid)
            {
                var ktTaiKhoan = db.TaiKhoans.FirstOrDefault(s => s.SoTaiKhoan.Contains(taiKhoan.SoTaiKhoan));

                if (ktTaiKhoan == null)
                {
                    ViewBag.MsgSTK = "Số tài khoản không tồn tại";
                    ViewBag.SoVe = SoVe;
                    ViewBag.Gia = tour.Gia;
                    ViewBag.NgayKhoiHanh = tour.NgayKhoiHanh;
                    ViewBag.TourID = tour.ID;
                    ViewBag.Ten = tour.Ten;
                    ViewBag.DiemDen = tour.DiaDiem1.Ten;
                    ViewBag.Button = 0;
                    ViewBag.NganHang = new SelectList(db.NganHangs, "ID", "Ten", taiKhoan.NganHangID);
                    return View();
                }
                else
                {
                    if(ktTaiKhoan.TenChuTaiKhoan.Contains(taiKhoan.TenChuTaiKhoan) != true)
                    {
                        ViewBag.MsgTenChuTK = "Tên bạn nhập không trùng với tên chủ tài khoản";
                        ViewBag.SoVe = SoVe;
                        ViewBag.Gia = tour.Gia;
                        ViewBag.NgayKhoiHanh = tour.NgayKhoiHanh;
                        ViewBag.TourID = tour.ID;
                        ViewBag.Ten = tour.Ten;
                        ViewBag.DiemDen = tour.DiaDiem1.Ten;
                        ViewBag.Button = 0;
                        ViewBag.NganHang = new SelectList(db.NganHangs, "ID", "Ten", taiKhoan.NganHangID);
                        return View();
                    }

                    string email = User.Identity.GetUserName();
                    var user = db.NguoiDungs.FirstOrDefault(s => s.Email.Contains(email));

                    if(user != null)
                    {
                        DateTime ngayDat = DateTime.Now;
                        DatTour datTour = new DatTour();
                        datTour.NgayDat = ngayDat;
                        datTour.NguoiDungID = user.ID;
                        datTour.SoLuong = SoVe;
                        datTour.TourID = TourID;
                        db.DatTours.Add(datTour);

                        decimal? tongtien = tour.Gia * SoVe;

                        GiaoDich giaoDich = new GiaoDich();
                        giaoDich.Tien = tongtien;
                        giaoDich.NgayGiaoDich = ngayDat;
                        giaoDich.SoDuBanDau = ktTaiKhoan.Tien;
                        giaoDich.SoDuSauGiaoDich = (ktTaiKhoan.Tien - tongtien);
                        db.GiaoDiches.Add(giaoDich);

                        ktTaiKhoan.Tien = (ktTaiKhoan.Tien - tongtien);
                        db.TaiKhoans.AddOrUpdate(ktTaiKhoan);

                        db.SaveChanges();
                        ViewBag.Msg = "Thanh toán thành công";
                        ViewBag.Button = 1;
                        ViewBag.Check = 1;
                        ViewBag.SoVe = SoVe;
                        ViewBag.Gia = tour.Gia;
                        ViewBag.NgayKhoiHanh = tour.NgayKhoiHanh;
                        ViewBag.TourID = tour.ID;
                        ViewBag.Ten = tour.Ten;
                        ViewBag.DiemDen = tour.DiaDiem1.Ten;
                        ViewBag.NganHang = new SelectList(db.NganHangs, "ID", "Ten", taiKhoan.NganHangID);
                        return View("Index");
                    }

                    ViewBag.Msg = "Thanh toán thất bại";
                    ViewBag.Check = 0;
                    ViewBag.SoVe = SoVe;
                    ViewBag.Gia = tour.Gia;
                    ViewBag.NgayKhoiHanh = tour.NgayKhoiHanh;
                    ViewBag.TourID = tour.ID;
                    ViewBag.Ten = tour.Ten;
                    ViewBag.DiemDen = tour.DiaDiem1.Ten;
                    ViewBag.Button = 0;
                    ViewBag.NganHang = new SelectList(db.NganHangs, "ID", "Ten", taiKhoan.NganHangID);
                    return View("Index");
                }
            }

            ViewBag.Msg = "Thanh toán thất bại";
            ViewBag.Check = 0;
            ViewBag.SoVe = SoVe;
            ViewBag.Gia = tour.Gia;
            ViewBag.NgayKhoiHanh = tour.NgayKhoiHanh;
            ViewBag.TourID = tour.ID;
            ViewBag.Ten = tour.Ten;
            ViewBag.DiemDen = tour.DiaDiem1.Ten;
            ViewBag.Button = 0;
            ViewBag.NganHang = new SelectList(db.NganHangs, "ID", "Ten", taiKhoan.NganHangID);
            return View("Index");
        }

    }
}

QLTour/QLTour/Views/BookTour/Index.cshtml
@model QLTour.Models.TaiKhoan

@{
    ViewBag.Title = "Đặt tour";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-5">
    <h1>Thanh Toán</h1>
    @{ 
        if(@ViewBag.Check == 0)
            {
                <p class="text-danger">@ViewBag.Msg</p>
            }
        else
            {
            <p class="text-success">@ViewBag.Msg</p>
            }
    }
    <form id="user-info-form">
        <div class="row">
            <div class="col-md-6 pt-5">
                <form id="tour-information-form">
                    <div>
                        <div class="row mb-2">
                            <div class="col-6" style="padding-left:20%;"><b>Tên Tour</b></div>
                            <div class="col-6"><span>@ViewBag.Ten</span></div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-6" style="padding-left:20%;"><b>Điểm đến du lịch</b></div>
                            <div class="col-6"><span>@ViewBag.DiemDen</span></div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-6" style="padding-left:20%;"><b>Ngày khởi hành</b></div>
                            <div class="col-6"><span>@String.Format("{0:d/M/yyyy}", ViewBag.NgayKhoiHanh)</span></div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-6" style="padding-left:20%;"><b>Giá Tour</b></div>
                            <div class="col-6"><span>@String.Format("{0:0,###}", ViewBag.Gia) VNĐ</span></div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-6" style="padding-left:20%;"><b>Số Vé</b></div>
                            <div class="col-6"><span>@ViewBag.SoVe</span></div>
                        </div>
                        <div class="d-flex justify-content-center"><hr style="width: 70%; background-color: #1953a7;"></div>
                        <div class="row mb-2">
                            <div class="col-6" style="padding-left:20%;"><b>Tổng tiền</b></div>
                            <div class="col-6"><h5 id="totalPrice">@String.Format("{0:0,###}", ViewBag.Gia * ViewBag.SoVe) VNĐ</h3></div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-6">
                <h2>Tài khoản ngân hàng</h2>
                @using (Html.BeginForm("Index", "BookTour", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    <input type="hidden" value="@ViewBag.TourID" id="TourID" name="TourID" />
                    <input type="hidden" value="@ViewBag.SoVe" id="SoVe" name="SoVe" class="form-control" />
                    <div class="mb-3">
                        <label for="bankName" class="form-label">Ngân hàng</label>
                        @Html.DropDownList("NganHang", null, htmlAttributes: new { @class = "form-control" })
                    </div>
                    <div class="mb-3">
                        <label for="accountName" class="form-label">Tên chủ tài khoản</label>
                        @Html.EditorFor(model => model.TenChuTaiKhoan, new { htmlAttributes = new { @class = "form-control" } })
                        <p class="text-danger">@ViewBag.MsgTenChuTK</p>
                    </div>
                    <div class="mb-3">
                        <label for="accountNumber" class="form-label">Số tài Khoản</label>
                        @Html.EditorFor(model => model.SoTaiKhoan, new { htmlAttributes = new { @class = "form-control" } })
                        <p class="text-danger">@ViewBag.MsgSTK</p>
                    </div>
                        if (ViewBag.Button == 1)
                        {
                             <button type="submit" class="btn btn-primary" disabled>Thanh toán</button>
                        }
                        else
                        { 
                            <button type="submit" class="btn btn-primary">Thanh toán</button>
                        }
                                            
                }
            </div>
        </div>
    </form>
</div>